// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = TextContentSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Title field in *Blog*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Date field in *Blog*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Author field in *Blog*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"blog_author">;

  /**
   * Category field in *Blog*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"blog_category">;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogAuthorDocumentDataSlicesSlice = never;

/**
 * Content for Blog Author documents
 */
interface BlogAuthorDocumentData {
  /**
   * Name field in *Blog Author*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Description field in *Blog Author*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_author.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Blog Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_author.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Job Title field in *Blog Author*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_author.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  job_title: prismic.RichTextField;

  /**
   * Slice Zone field in *Blog Author*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_author.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogAuthorDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_author.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_author.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_author.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Author document from Prismic
 *
 * - **API ID**: `blog_author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogAuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogAuthorDocumentData>,
    "blog_author",
    Lang
  >;

type BlogCategoryDocumentDataSlicesSlice = never;

/**
 * Content for Blog Category documents
 */
interface BlogCategoryDocumentData {
  /**
   * Title field in *Blog Category*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Icon field in *Blog Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Description field in *Blog Category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *Blog Category*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogCategoryDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_category.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_category.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Category document from Prismic
 *
 * - **API ID**: `blog_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategoryDocumentData>,
    "blog_category",
    Lang
  >;

/**
 * Item in *Blog Home → Rolling Title*
 */
export interface BlogHomeDocumentDataRollingTitleItem {
  /**
   * Title Part field in *Blog Home → Rolling Title*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.rolling_title[].title_part
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_part: prismic.KeyTextField;
}

type BlogHomeDocumentDataSlicesSlice = BlogPostSliderSlice;

/**
 * Content for Blog Home documents
 */
interface BlogHomeDocumentData {
  /**
   * Title field in *Blog Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Rolling Title field in *Blog Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.rolling_title[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rolling_title: prismic.GroupField<
    Simplify<BlogHomeDocumentDataRollingTitleItem>
  >;

  /**
   * Slice Zone field in *Blog Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogHomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Home document from Prismic
 *
 * - **API ID**: `blog_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogHomeDocumentData>,
    "blog_home",
    Lang
  >;

type ContactDocumentDataSlicesSlice = ContactFormSlice | HeroSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type ContactHomeDocumentDataSlicesSlice = never;

/**
 * Content for Contact Home documents
 */
interface ContactHomeDocumentData {
  /**
   * Slice Zone field in *Contact Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactHomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact Home document from Prismic
 *
 * - **API ID**: `contact_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactHomeDocumentData>,
    "contact_home",
    Lang
  >;

type EnterpriseHomeDocumentDataSlicesSlice =
  | CardGridSlice
  | BenefitsSlice
  | CallToActionSlice
  | FeaturesSlice
  | HeroSlice;

/**
 * Content for Enterprise Home documents
 */
interface EnterpriseHomeDocumentData {
  /**
   * Slice Zone field in *Enterprise Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: enterprise_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EnterpriseHomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Enterprise Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: enterprise_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Enterprise Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: enterprise_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Enterprise Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: enterprise_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Enterprise Home document from Prismic
 *
 * - **API ID**: `enterprise_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EnterpriseHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EnterpriseHomeDocumentData>,
    "enterprise_home",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | FeaturesSlice
  | HowItWorksSlice
  | BenefitsSlice
  | HeroSlice
  | CallToActionSlice;

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type LayoutDocumentDataSlicesSlice = MenuItemSlice;

type LayoutDocumentDataSlices1Slice = FooterColumnSlice;

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * CTA field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.cta
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LayoutDocumentDataSlicesSlice> /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices1[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<LayoutDocumentDataSlices1Slice> /**
   * Links field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links
   * - **Tab**: Legal Bar
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

type LegalDocumentDataSlicesSlice =
  | LegalTableSlice
  | LegalTextSlice
  | LegalHeroSlice;

/**
 * Content for Legal documents
 */
interface LegalDocumentData {
  /**
   * Slice Zone field in *Legal*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LegalDocumentDataSlicesSlice> /**
   * Meta Title field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legal.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legal.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Legal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Legal document from Prismic
 *
 * - **API ID**: `legal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LegalDocumentData>, "legal", Lang>;

type LegalHomeDocumentDataSlicesSlice =
  | CardGridSlice
  | LegalHeroSlice
  | LegalTextSlice;

/**
 * Content for Legal Home documents
 */
interface LegalHomeDocumentData {
  /**
   * Slice Zone field in *Legal Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LegalHomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Legal Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legal_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Legal Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legal_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Legal Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Legal Home document from Prismic
 *
 * - **API ID**: `legal_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LegalHomeDocumentData>,
    "legal_home",
    Lang
  >;

type MarketingDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Marketing documents
 */
interface MarketingDocumentData {
  /**
   * Slice Zone field in *Marketing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: marketing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MarketingDocumentDataSlicesSlice> /**
   * Meta Title field in *Marketing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: marketing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Marketing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: marketing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Marketing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marketing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Marketing document from Prismic
 *
 * - **API ID**: `marketing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MarketingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MarketingDocumentData>,
    "marketing",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | BenefitsSlice
  | FeaturesSlice
  | FeaturedSlice
  | HeroSlice
  | CallToActionSlice;

/**
 * Content for Platform documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Platform*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Platform*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Platform*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Platform*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Platform document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ServicesDocumentDataSlicesSlice =
  | CallToActionSlice
  | FeaturesSlice
  | HeroSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * CopyrightName field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Kopexa
   * - **API ID Path**: settings.copyrightname
   * - **Tab**: Copyright
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyrightname: prismic.KeyTextField;

  /**
   * CopyrightSince field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 2020
   * - **API ID Path**: settings.copyrightsince
   * - **Tab**: Copyright
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyrightsince: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type SubMenuDocumentDataSlicesSlice = SubMenuItemSlice | HeadingSlice;

type SubMenuDocumentDataSlices1Slice = SubMenuItemSlice | HeadingSlice;

type SubMenuDocumentDataSlices2Slice = HeadingSlice | SubMenuItemSlice;

/**
 * Content for Sub menu documents
 */
interface SubMenuDocumentData {
  /**
   * Slice Zone field in *Sub menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices[]
   * - **Tab**: Column 1
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubMenuDocumentDataSlicesSlice> /**
   * Slice Zone field in *Sub menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices1[]
   * - **Tab**: Column 2
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<SubMenuDocumentDataSlices1Slice> /**
   * Slice Zone field in *Sub menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices2[]
   * - **Tab**: Column 3
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<SubMenuDocumentDataSlices2Slice>;
}

/**
 * Sub menu document from Prismic
 *
 * - **API ID**: `sub_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SubMenuDocumentData>,
    "sub_menu",
    Lang
  >;

type SupportDocumentDataSlicesSlice = FeaturesSlice | HeroSlice;

/**
 * Content for Support documents
 */
interface SupportDocumentData {
  /**
   * Slice Zone field in *Support*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: support.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SupportDocumentDataSlicesSlice> /**
   * Meta Title field in *Support*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: support.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Support*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: support.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Support*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: support.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Support document from Prismic
 *
 * - **API ID**: `support`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SupportDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SupportDocumentData>,
    "support",
    Lang
  >;

type SupportHomeDocumentDataSlicesSlice =
  | CallToActionSlice
  | CardGridSlice
  | HeroSlice;

/**
 * Content for Support Home documents
 */
interface SupportHomeDocumentData {
  /**
   * Slice Zone field in *Support Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: support_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SupportHomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Support Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: support_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Support Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: support_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Support Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: support_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Support Home document from Prismic
 *
 * - **API ID**: `support_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SupportHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SupportHomeDocumentData>,
    "support_home",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | BlogAuthorDocument
  | BlogCategoryDocument
  | BlogHomeDocument
  | ContactDocument
  | ContactHomeDocument
  | EnterpriseHomeDocument
  | HomePageDocument
  | LayoutDocument
  | LegalDocument
  | LegalHomeDocument
  | MarketingDocument
  | PageDocument
  | ServicesDocument
  | SettingsDocument
  | SubMenuDocument
  | SupportDocument
  | SupportHomeDocument;

/**
 * Primary content in *Benefits → Text Illustration → Primary*
 */
export interface BenefitsSliceTextIllustrationPrimary {
  /**
   * Heading field in *Benefits → Text Illustration → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.textIllustration.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Image field in *Benefits → Text Illustration → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.textIllustration.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Second Column field in *Benefits → Text Illustration → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.textIllustration.primary.second_column
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_column: prismic.RichTextField;
}

/**
 * Text Illustration variation for Benefits Slice
 *
 * - **API ID**: `textIllustration`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSliceTextIllustration = prismic.SharedSliceVariation<
  "textIllustration",
  Simplify<BenefitsSliceTextIllustrationPrimary>,
  never
>;

/**
 * Primary content in *Benefits → Image Text List Left → Primary*
 */
export interface BenefitsSliceImageTextListLeftPrimary {
  /**
   * Heading field in *Benefits → Image Text List Left → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.imageTextListLeft.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *Benefits → Image Text List Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.imageTextListLeft.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Image field in *Benefits → Image Text List Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.imageTextListLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Text List Left variation for Benefits Slice
 *
 * - **API ID**: `imageTextListLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSliceImageTextListLeft = prismic.SharedSliceVariation<
  "imageTextListLeft",
  Simplify<BenefitsSliceImageTextListLeftPrimary>,
  never
>;

/**
 * Primary content in *Benefits → Image Text List Right → Primary*
 */
export interface BenefitsSliceImageTextListRightPrimary {
  /**
   * Heading field in *Benefits → Image Text List Right → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.imageTextListRight.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *Benefits → Image Text List Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.imageTextListRight.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Image field in *Benefits → Image Text List Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.imageTextListRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Text List Right variation for Benefits Slice
 *
 * - **API ID**: `imageTextListRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSliceImageTextListRight = prismic.SharedSliceVariation<
  "imageTextListRight",
  Simplify<BenefitsSliceImageTextListRightPrimary>,
  never
>;

/**
 * Slice variation for *Benefits*
 */
type BenefitsSliceVariation =
  | BenefitsSliceTextIllustration
  | BenefitsSliceImageTextListLeft
  | BenefitsSliceImageTextListRight;

/**
 * Benefits Shared Slice
 *
 * - **API ID**: `benefits`
 * - **Description**: Benefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSlice = prismic.SharedSlice<
  "benefits",
  BenefitsSliceVariation
>;

/**
 * Item in *BlogPostSlider → Default → Primary → Tags*
 */
export interface BlogPostSliderSliceDefaultPrimaryTagsItem {
  /**
   * tag field in *BlogPostSlider → Default → Primary → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_slider.default.primary.tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *BlogPostSlider → Default → Primary*
 */
export interface BlogPostSliderSliceDefaultPrimary {
  /**
   * Title field in *BlogPostSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_slider.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * CTA Link field in *BlogPostSlider → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_slider.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Description field in *BlogPostSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_slider.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tags field in *BlogPostSlider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_slider.default.primary.tags[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tags: prismic.GroupField<Simplify<BlogPostSliderSliceDefaultPrimaryTagsItem>>;
}

/**
 * Default variation for BlogPostSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostSliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostSlider*
 */
type BlogPostSliderSliceVariation = BlogPostSliderSliceDefault;

/**
 * BlogPostSlider Shared Slice
 *
 * - **API ID**: `blog_post_slider`
 * - **Description**: BlogPostSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSliderSlice = prismic.SharedSlice<
  "blog_post_slider",
  BlogPostSliderSliceVariation
>;

/**
 * Item in *CallToAction → Default → Primary → Links*
 */
export interface CallToActionSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *CallToAction → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "default" | "outline" | "link"
  >;

  /**
   * Description field in *CallToAction → Default → Primary → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.links[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Theme field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Inherit from Parent
   * - **API ID Path**: call_to_action.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "Inherit from Parent" | "Light" | "Dark",
    "filled"
  >;

  /**
   * Title field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Links field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<CallToActionSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → Illustrated → Primary*
 */
export interface CallToActionSliceIllustratedPrimary {
  /**
   * Theme field in *CallToAction → Illustrated → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Inherit from Parent
   * - **API ID Path**: call_to_action.illustrated.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "Inherit from Parent" | "Light" | "Dark",
    "filled"
  >;

  /**
   * Title field in *CallToAction → Illustrated → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.illustrated.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *CallToAction → Illustrated → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.illustrated.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *CallToAction → Illustrated → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.illustrated.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Illustrated variation for CallToAction Slice
 *
 * - **API ID**: `illustrated`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceIllustrated = prismic.SharedSliceVariation<
  "illustrated",
  Simplify<CallToActionSliceIllustratedPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → Slim → Primary*
 */
export interface CallToActionSliceSlimPrimary {
  /**
   * Theme field in *CallToAction → Slim → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Inherit from Parent
   * - **API ID Path**: call_to_action.slim.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "Inherit from Parent" | "Light" | "Dark",
    "filled"
  >;

  /**
   * Title field in *CallToAction → Slim → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.slim.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subheading field in *CallToAction → Slim → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.slim.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Image field in *CallToAction → Slim → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.slim.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *CallToAction → Slim → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.slim.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "default" | "outline"
  >;
}

/**
 * Slim variation for CallToAction Slice
 *
 * - **API ID**: `slim`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceSlim = prismic.SharedSliceVariation<
  "slim",
  Simplify<CallToActionSliceSlimPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceIllustrated
  | CallToActionSliceSlim;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Item in *CardGrid → Default → Primary → Cards*
 */
export interface CardGridSliceDefaultPrimaryCardsItem {
  /**
   * Heading field in *CardGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.default.primary.cards[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *CardGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.default.primary.cards[].subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Link field in *CardGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *CardGrid → Default → Primary*
 */
export interface CardGridSliceDefaultPrimary {
  /**
   * Heading field in *CardGrid → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Cards field in *CardGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<CardGridSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for CardGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardGrid*
 */
type CardGridSliceVariation = CardGridSliceDefault;

/**
 * CardGrid Shared Slice
 *
 * - **API ID**: `card_grid`
 * - **Description**: CardGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGridSlice = prismic.SharedSlice<
  "card_grid",
  CardGridSliceVariation
>;

/**
 * Item in *ContactForm → Default → Primary → Fields*
 */
export interface ContactFormSliceDefaultPrimaryFieldsItem {
  /**
   * Field Label field in *ContactForm → Default → Primary → Fields*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.fields[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Field Placeholder field in *ContactForm → Default → Primary → Fields*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.fields[].placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Field Type field in *ContactForm → Default → Primary → Fields*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Text
   * - **API ID Path**: contact_form.default.primary.fields[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Text" | "Email" | "Textarea", "filled">;
}

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Title field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: The title of the section
   * - **API ID Path**: contact_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your product
   * - **API ID Path**: contact_form.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Fields field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.fields[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  fields: prismic.GroupField<
    Simplify<ContactFormSliceDefaultPrimaryFieldsItem>
  >;

  /**
   * Submit Button Label field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.submitButtonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submitButtonLabel: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Item in *Featured → Default → Primary → Features*
 */
export interface FeaturedSliceDefaultPrimaryFeaturesItem {
  /**
   * Icon field in *Featured → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Heading field in *Featured → Default → Primary → Features*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.features[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Featured → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *Featured → Default → Primary → links*
 */
export interface FeaturedSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *Featured → Default → Primary → links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "default" | "outline" | "ghost" | "link"
  >;
}

/**
 * Primary content in *Featured → Default → Primary*
 */
export interface FeaturedSliceDefaultPrimary {
  /**
   * Theme field in *Featured → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: light
   * - **API ID Path**: featured.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"light" | "dark", "filled">;

  /**
   * Heading field in *Featured → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *Featured → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Image field in *Featured → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Features field in *Featured → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<FeaturedSliceDefaultPrimaryFeaturesItem>
  >;

  /**
   * links field in *Featured → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FeaturedSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for Featured Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Featured*
 */
type FeaturedSliceVariation = FeaturedSliceDefault;

/**
 * Featured Shared Slice
 *
 * - **API ID**: `featured`
 * - **Description**: Featured
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedSlice = prismic.SharedSlice<
  "featured",
  FeaturedSliceVariation
>;

/**
 * Item in *Features → Four Columns → Primary → Features*
 */
export interface FeaturesSliceFourColumnsPrimaryFeaturesItem {
  /**
   * Heading field in *Features → Four Columns → Primary → Features*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: features.fourColumns.primary.features[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *Features → Four Columns → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.fourColumns.primary.features[].subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Link field in *Features → Four Columns → Primary → Features*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.fourColumns.primary.features[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon field in *Features → Four Columns → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.fourColumns.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *Features → Four Columns → Primary*
 */
export interface FeaturesSliceFourColumnsPrimary {
  /**
   * Theme field in *Features → Four Columns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: light
   * - **API ID Path**: features.fourColumns.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<"light" | "dark", "filled">;

  /**
   * Heading field in *Features → Four Columns → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: features.fourColumns.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *Features → Four Columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.fourColumns.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Features field in *Features → Four Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features.fourColumns.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<FeaturesSliceFourColumnsPrimaryFeaturesItem>
  >;
}

/**
 * Four Columns variation for Features Slice
 *
 * - **API ID**: `fourColumns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceFourColumns = prismic.SharedSliceVariation<
  "fourColumns",
  Simplify<FeaturesSliceFourColumnsPrimary>,
  never
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceFourColumns;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *FooterColumn → Default → Primary*
 */
export interface FooterColumnSliceDefaultPrimary {
  /**
   * Heading field in *FooterColumn → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Links field in *FooterColumn → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.default.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Column field in *FooterColumn → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: footer_column.default.primary.column
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  column: prismic.SelectField<"1" | "2" | "3" | "4", "filled">;
}

/**
 * Default variation for FooterColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterColumnSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *FooterColumn → Brand → Primary*
 */
export interface FooterColumnSliceBrandPrimary {
  /**
   * Heading field in *FooterColumn → Brand → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.brand.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Links field in *FooterColumn → Brand → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_column.brand.primary.links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Column field in *FooterColumn → Brand → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: footer_column.brand.primary.column
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  column: prismic.SelectField<"1" | "2" | "3" | "4", "filled">;
}

/**
 * Brand variation for FooterColumn Slice
 *
 * - **API ID**: `brand`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterColumnSliceBrand = prismic.SharedSliceVariation<
  "brand",
  Simplify<FooterColumnSliceBrandPrimary>,
  never
>;

/**
 * Slice variation for *FooterColumn*
 */
type FooterColumnSliceVariation =
  | FooterColumnSliceDefault
  | FooterColumnSliceBrand;

/**
 * FooterColumn Shared Slice
 *
 * - **API ID**: `footer_column`
 * - **Description**: FooterColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterColumnSlice = prismic.SharedSlice<
  "footer_column",
  FooterColumnSliceVariation
>;

/**
 * Primary content in *Heading → Default → Primary*
 */
export interface HeadingSliceDefaultPrimary {
  /**
   * Label field in *Heading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for Heading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Heading*
 */
type HeadingSliceVariation = HeadingSliceDefault;

/**
 * Heading Shared Slice
 *
 * - **API ID**: `heading`
 * - **Description**: Heading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingSlice = prismic.SharedSlice<
  "heading",
  HeadingSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → CallToActions*
 */
export interface HeroSliceDefaultPrimaryCalltoactionsItem {
  /**
   * Link field in *Hero → Default → Primary → CallToActions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.calltoactions[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "default" | "outline"
  >;
}

/**
 * Item in *Hero → Centered Background → Primary → CallToActions*
 */
export interface HeroSliceCenteredBackgroundPrimaryCalltoactionsItem {
  /**
   * Link field in *Hero → Centered Background → Primary → CallToActions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centeredBackground.primary.calltoactions[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "default" | "outline"
  >;
}

/**
 * Item in *Hero → Centered → Primary → CallToActions*
 */
export interface HeroSliceCenteredPrimaryCalltoactionsItem {
  /**
   * Link field in *Hero → Centered → Primary → CallToActions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centered.primary.calltoactions[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "default" | "outline"
  >;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * CallToActions field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.calltoactions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  calltoactions: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryCalltoactionsItem>
  >;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Centered Background → Primary*
 */
export interface HeroSliceCenteredBackgroundPrimary {
  /**
   * Eyebrow field in *Hero → Centered Background → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centeredBackground.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Hero → Centered Background → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centeredBackground.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *Hero → Centered Background → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centeredBackground.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * CallToActions field in *Hero → Centered Background → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centeredBackground.primary.calltoactions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  calltoactions: prismic.GroupField<
    Simplify<HeroSliceCenteredBackgroundPrimaryCalltoactionsItem>
  >;

  /**
   * Image field in *Hero → Centered Background → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centeredBackground.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Centered Background variation for Hero Slice
 *
 * - **API ID**: `centeredBackground`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceCenteredBackground = prismic.SharedSliceVariation<
  "centeredBackground",
  Simplify<HeroSliceCenteredBackgroundPrimary>,
  never
>;

/**
 * Primary content in *Hero → Centered → Primary*
 */
export interface HeroSliceCenteredPrimary {
  /**
   * Heading field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centered.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centered.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * CallToActions field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centered.primary.calltoactions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  calltoactions: prismic.GroupField<
    Simplify<HeroSliceCenteredPrimaryCalltoactionsItem>
  >;

  /**
   * Eyebrow field in *Hero → Centered → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centered.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;
}

/**
 * Centered variation for Hero Slice
 *
 * - **API ID**: `centered`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceCentered = prismic.SharedSliceVariation<
  "centered",
  Simplify<HeroSliceCenteredPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceCenteredBackground
  | HeroSliceCentered;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *HowItWorks → Default → Primary → Solutions*
 */
export interface HowItWorksSliceDefaultPrimarySolutionsItem {
  /**
   * Heading field in *HowItWorks → Default → Primary → Solutions*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.default.primary.solutions[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *HowItWorks → Default → Primary → Solutions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.default.primary.solutions[].subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Image field in *HowItWorks → Default → Primary → Solutions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.default.primary.solutions[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HowItWorks → Default → Primary*
 */
export interface HowItWorksSliceDefaultPrimary {
  /**
   * Heading field in *HowItWorks → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Solutions field in *HowItWorks → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.default.primary.solutions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  solutions: prismic.GroupField<
    Simplify<HowItWorksSliceDefaultPrimarySolutionsItem>
  >;

  /**
   * Subheading field in *HowItWorks → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;
}

/**
 * Default variation for HowItWorks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowItWorksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HowItWorksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HowItWorks*
 */
type HowItWorksSliceVariation = HowItWorksSliceDefault;

/**
 * HowItWorks Shared Slice
 *
 * - **API ID**: `how_it_works`
 * - **Description**: HowItWorks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowItWorksSlice = prismic.SharedSlice<
  "how_it_works",
  HowItWorksSliceVariation
>;

/**
 * Primary content in *LegalHero → Default → Primary*
 */
export interface LegalHeroSliceDefaultPrimary {
  /**
   * Heading field in *LegalHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *LegalHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;
}

/**
 * Default variation for LegalHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LegalHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LegalHero*
 */
type LegalHeroSliceVariation = LegalHeroSliceDefault;

/**
 * LegalHero Shared Slice
 *
 * - **API ID**: `legal_hero`
 * - **Description**: LegalHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalHeroSlice = prismic.SharedSlice<
  "legal_hero",
  LegalHeroSliceVariation
>;

/**
 * Primary content in *LegalTable → One Column → Primary*
 */
export interface LegalTableSliceDefaultPrimary {
  /**
   * Table title field in *LegalTable → One Column → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Table Title
   * - **API ID Path**: legal_table.default.primary.table_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  table_title: prismic.TitleField;
}

/**
 * Primary content in *LegalTable → Items*
 */
export interface LegalTableSliceDefaultItem {
  /**
   * Column 1 field in *LegalTable → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Column 1 content...
   * - **API ID Path**: legal_table.items[].cell
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cell: prismic.RichTextField;
}

/**
 * One Column variation for LegalTable Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalTableSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LegalTableSliceDefaultPrimary>,
  Simplify<LegalTableSliceDefaultItem>
>;

/**
 * Primary content in *LegalTable → Two Column → Primary*
 */
export interface LegalTableSliceTwoColumnPrimary {
  /**
   * Table title field in *LegalTable → Two Column → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Table Title
   * - **API ID Path**: legal_table.twoColumn.primary.table_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  table_title: prismic.TitleField;
}

/**
 * Primary content in *LegalTable → Items*
 */
export interface LegalTableSliceTwoColumnItem {
  /**
   * Column 1 field in *LegalTable → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Column 1 content...
   * - **API ID Path**: legal_table.items[].cell
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cell: prismic.RichTextField;

  /**
   * Column 2 field in *LegalTable → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Column 2 content...
   * - **API ID Path**: legal_table.items[].cellTwo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cellTwo: prismic.RichTextField;
}

/**
 * Two Column variation for LegalTable Slice
 *
 * - **API ID**: `twoColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalTableSliceTwoColumn = prismic.SharedSliceVariation<
  "twoColumn",
  Simplify<LegalTableSliceTwoColumnPrimary>,
  Simplify<LegalTableSliceTwoColumnItem>
>;

/**
 * Slice variation for *LegalTable*
 */
type LegalTableSliceVariation =
  | LegalTableSliceDefault
  | LegalTableSliceTwoColumn;

/**
 * LegalTable Shared Slice
 *
 * - **API ID**: `legal_table`
 * - **Description**: LegalTable
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalTableSlice = prismic.SharedSlice<
  "legal_table",
  LegalTableSliceVariation
>;

/**
 * Primary content in *LegalText → Default → Primary*
 */
export interface LegalTextSliceDefaultPrimary {
  /**
   * Content field in *LegalText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for LegalText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LegalTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LegalText*
 */
type LegalTextSliceVariation = LegalTextSliceDefault;

/**
 * LegalText Shared Slice
 *
 * - **API ID**: `legal_text`
 * - **Description**: LegalText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalTextSlice = prismic.SharedSlice<
  "legal_text",
  LegalTextSliceVariation
>;

/**
 * Primary content in *MenuItem → Default → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Label field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MenuItem → With Sub Menu → Primary*
 */
export interface MenuItemSliceWithSubMenuPrimary {
  /**
   * Label field in *MenuItem → With Sub Menu → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.withSubMenu.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *MenuItem → With Sub Menu → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.withSubMenu.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Sub Menu field in *MenuItem → With Sub Menu → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.withSubMenu.primary.subMenu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subMenu: prismic.ContentRelationshipField<"sub_menu">;
}

/**
 * With Sub Menu variation for MenuItem Slice
 *
 * - **API ID**: `withSubMenu`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceWithSubMenu = prismic.SharedSliceVariation<
  "withSubMenu",
  Simplify<MenuItemSliceWithSubMenuPrimary>,
  never
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault | MenuItemSliceWithSubMenu;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

/**
 * Primary content in *SubMenuItem → Default → Primary*
 */
export interface SubMenuItemSliceDefaultPrimary {
  /**
   * Link field in *SubMenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Label field in *SubMenuItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for SubMenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubMenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SubMenuItem → Button → Primary*
 */
export interface SubMenuItemSliceButtonPrimary {
  /**
   * Link field in *SubMenuItem → Button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.button.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Label field in *SubMenuItem → Button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.button.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Button variation for SubMenuItem Slice
 *
 * - **API ID**: `button`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceButton = prismic.SharedSliceVariation<
  "button",
  Simplify<SubMenuItemSliceButtonPrimary>,
  never
>;

/**
 * Primary content in *SubMenuItem → Box → Primary*
 */
export interface SubMenuItemSliceBoxPrimary {
  /**
   * Link field in *SubMenuItem → Box → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.box.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Label field in *SubMenuItem → Box → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.box.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Description field in *SubMenuItem → Box → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.box.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Box variation for SubMenuItem Slice
 *
 * - **API ID**: `box`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceBox = prismic.SharedSliceVariation<
  "box",
  Simplify<SubMenuItemSliceBoxPrimary>,
  never
>;

/**
 * Primary content in *SubMenuItem → withIcon → Primary*
 */
export interface SubMenuItemSliceWithIconPrimary {
  /**
   * Link field in *SubMenuItem → withIcon → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.withIcon.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Label field in *SubMenuItem → withIcon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.withIcon.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Icon field in *SubMenuItem → withIcon → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.withIcon.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * withIcon variation for SubMenuItem Slice
 *
 * - **API ID**: `withIcon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceWithIcon = prismic.SharedSliceVariation<
  "withIcon",
  Simplify<SubMenuItemSliceWithIconPrimary>,
  never
>;

/**
 * Slice variation for *SubMenuItem*
 */
type SubMenuItemSliceVariation =
  | SubMenuItemSliceDefault
  | SubMenuItemSliceButton
  | SubMenuItemSliceBox
  | SubMenuItemSliceWithIcon;

/**
 * SubMenuItem Shared Slice
 *
 * - **API ID**: `sub_menu_item`
 * - **Description**: SubMenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSlice = prismic.SharedSlice<
  "sub_menu_item",
  SubMenuItemSliceVariation
>;

/**
 * Primary content in *TextContent → Default → Primary*
 */
export interface TextContentSliceDefaultPrimary {
  /**
   * Content field in *TextContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextContent*
 */
type TextContentSliceVariation = TextContentSliceDefault;

/**
 * TextContent Shared Slice
 *
 * - **API ID**: `text_content`
 * - **Description**: TextContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextContentSlice = prismic.SharedSlice<
  "text_content",
  TextContentSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogAuthorDocument,
      BlogAuthorDocumentData,
      BlogAuthorDocumentDataSlicesSlice,
      BlogCategoryDocument,
      BlogCategoryDocumentData,
      BlogCategoryDocumentDataSlicesSlice,
      BlogHomeDocument,
      BlogHomeDocumentData,
      BlogHomeDocumentDataRollingTitleItem,
      BlogHomeDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      ContactHomeDocument,
      ContactHomeDocumentData,
      ContactHomeDocumentDataSlicesSlice,
      EnterpriseHomeDocument,
      EnterpriseHomeDocumentData,
      EnterpriseHomeDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataSlicesSlice,
      LayoutDocumentDataSlices1Slice,
      LegalDocument,
      LegalDocumentData,
      LegalDocumentDataSlicesSlice,
      LegalHomeDocument,
      LegalHomeDocumentData,
      LegalHomeDocumentDataSlicesSlice,
      MarketingDocument,
      MarketingDocumentData,
      MarketingDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SubMenuDocument,
      SubMenuDocumentData,
      SubMenuDocumentDataSlicesSlice,
      SubMenuDocumentDataSlices1Slice,
      SubMenuDocumentDataSlices2Slice,
      SupportDocument,
      SupportDocumentData,
      SupportDocumentDataSlicesSlice,
      SupportHomeDocument,
      SupportHomeDocumentData,
      SupportHomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      BenefitsSlice,
      BenefitsSliceTextIllustrationPrimary,
      BenefitsSliceImageTextListLeftPrimary,
      BenefitsSliceImageTextListRightPrimary,
      BenefitsSliceVariation,
      BenefitsSliceTextIllustration,
      BenefitsSliceImageTextListLeft,
      BenefitsSliceImageTextListRight,
      BlogPostSliderSlice,
      BlogPostSliderSliceDefaultPrimaryTagsItem,
      BlogPostSliderSliceDefaultPrimary,
      BlogPostSliderSliceVariation,
      BlogPostSliderSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimaryLinksItem,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceIllustratedPrimary,
      CallToActionSliceSlimPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceIllustrated,
      CallToActionSliceSlim,
      CardGridSlice,
      CardGridSliceDefaultPrimaryCardsItem,
      CardGridSliceDefaultPrimary,
      CardGridSliceVariation,
      CardGridSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimaryFieldsItem,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      FeaturedSlice,
      FeaturedSliceDefaultPrimaryFeaturesItem,
      FeaturedSliceDefaultPrimaryLinksItem,
      FeaturedSliceDefaultPrimary,
      FeaturedSliceVariation,
      FeaturedSliceDefault,
      FeaturesSlice,
      FeaturesSliceFourColumnsPrimaryFeaturesItem,
      FeaturesSliceFourColumnsPrimary,
      FeaturesSliceVariation,
      FeaturesSliceFourColumns,
      FooterColumnSlice,
      FooterColumnSliceDefaultPrimary,
      FooterColumnSliceBrandPrimary,
      FooterColumnSliceVariation,
      FooterColumnSliceDefault,
      FooterColumnSliceBrand,
      HeadingSlice,
      HeadingSliceDefaultPrimary,
      HeadingSliceVariation,
      HeadingSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryCalltoactionsItem,
      HeroSliceDefaultPrimary,
      HeroSliceCenteredBackgroundPrimaryCalltoactionsItem,
      HeroSliceCenteredBackgroundPrimary,
      HeroSliceCenteredPrimaryCalltoactionsItem,
      HeroSliceCenteredPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceCenteredBackground,
      HeroSliceCentered,
      HowItWorksSlice,
      HowItWorksSliceDefaultPrimarySolutionsItem,
      HowItWorksSliceDefaultPrimary,
      HowItWorksSliceVariation,
      HowItWorksSliceDefault,
      LegalHeroSlice,
      LegalHeroSliceDefaultPrimary,
      LegalHeroSliceVariation,
      LegalHeroSliceDefault,
      LegalTableSlice,
      LegalTableSliceDefaultPrimary,
      LegalTableSliceDefaultItem,
      LegalTableSliceTwoColumnPrimary,
      LegalTableSliceTwoColumnItem,
      LegalTableSliceVariation,
      LegalTableSliceDefault,
      LegalTableSliceTwoColumn,
      LegalTextSlice,
      LegalTextSliceDefaultPrimary,
      LegalTextSliceVariation,
      LegalTextSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceWithSubMenuPrimary,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      MenuItemSliceWithSubMenu,
      SubMenuItemSlice,
      SubMenuItemSliceDefaultPrimary,
      SubMenuItemSliceButtonPrimary,
      SubMenuItemSliceBoxPrimary,
      SubMenuItemSliceWithIconPrimary,
      SubMenuItemSliceVariation,
      SubMenuItemSliceDefault,
      SubMenuItemSliceButton,
      SubMenuItemSliceBox,
      SubMenuItemSliceWithIcon,
      TextContentSlice,
      TextContentSliceDefaultPrimary,
      TextContentSliceVariation,
      TextContentSliceDefault,
    };
  }
}
