// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  benefits: dynamic(() => import("./Benefits")),
  blog_post_slider: dynamic(() => import("./BlogPostSlider")),
  call_to_action: dynamic(() => import("./CallToAction")),
  card_grid: dynamic(() => import("./CardGrid")),
  contact_form: dynamic(() => import("./ContactForm")),
  featured: dynamic(() => import("./Featured")),
  features: dynamic(() => import("./Features")),
  footer_column: dynamic(() => import("./FooterColumn")),
  heading: dynamic(() => import("./Heading")),
  hero: dynamic(() => import("./Hero")),
  how_it_works: dynamic(() => import("./HowItWorks")),
  legal_hero: dynamic(() => import("./LegalHero")),
  legal_table: dynamic(() => import("./LegalTable")),
  legal_text: dynamic(() => import("./LegalText")),
  menu_item: dynamic(() => import("./MenuItem")),
  sub_menu_item: dynamic(() => import("./SubMenuItem")),
  text_content: dynamic(() => import("./TextContent")),
};
