import type { Metadata } from "next";
import "../globals.css";
import { PrivacyProvider } from "@/providers/privacy";
import { GoogleAnalytics } from "@/components/analytics/google-analytics";
import { GoogleTagManager } from "@/components/analytics/google-tag-manager";
import { Providers } from "@/providers";
import { PrivacyBanner } from "@/components/privacy-banner";
import { Header } from "@/components/layout/header";
import { Manrope } from "next/font/google";
import { Footer } from "@/components/layout/footer";

const ManropeFont = Manrope({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrivacyProvider>
        <head>
          <link href="https://www.googletagmanager.com" rel="preconnect" />
          <link href="https://www.google-analytics.com" rel="preconnect" />
          <GoogleAnalytics />
        </head>
        <body className={`antialiased ${ManropeFont.variable}`}>
          <GoogleTagManager />
          <Providers>
            <Header />
            <main className="block">{children}</main>

            <Footer />
            <PrivacyBanner />
          </Providers>
        </body>
      </PrivacyProvider>
    </html>
  );
}
